// SPDX-FileCopyrightText: 2025 adecc Systemhaus GmbH
// SPDX-License-Identifier: GPL-3.0-or-later

/**
  \file 
  \brief IDL definition of the Basics module for CORBA-based common types.
 
  \details Defines common structures / data types for working with corba communication.
 
  \copyright Copyright © 2025 adecc Systemhaus GmbH  
             This program is free software: you can redistribute it and/or modify it  
             under the terms of the GNU General Public License, version 3,
             as published by the Free Software Foundation.
 
             This program is distributed in the hope that it will be useful,
             but WITHOUT ANY WARRANTY; without even the implied warranty of
             MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
             See the GNU General Public License for more details.
			
             You should have received a copy of the GNU General Public License
             along with this program. If not, see <https://www.gnu.org/licenses/>.
 
  \note This Software is part of the adecc Scholar project – Free educational materials for modern C++.
 */


/// Corba namespace / module for the common defined types and interfaces.
module Basics {


   /**
     \brief Represents a point in time as Unix timestamp in milliseconds.
   */
   struct TimePoint {
      long long milliseconds_since_epoch;  ///< Unix timestamp, milliseconds since the Unix epoch (1970-01-01T00:00:00Z).
      };
	   
	   
    /**
      \brief Represents a calendar date using year, month, and day.
    */	   
   struct YearMonthDay {
      long year;   ///< Full year, e.g., 2025
      short month; ///< Month [1–12]
      short day;   ///< Day [1–31]
      };

   /**
     \brief Interface for all servants which can be delete from client
    */
   interface DestroyableInterface {
      /**
        \brief Destroys this object on the server side.
        \details Base class for interfaces with an destroy method for transient
                 Objects on the server
      */
      void destroy();
   };
};
