#include "basics.idl"

module WeatherAPI{

   interface WeatherService {
      readonly attribute Basics::Optional_Time   sunrise;
      readonly attribute Basics::Optional_Time   sunset;
      readonly attribute Basics::Optional_Double temperature;
      readonly attribute Basics::Optional_Double pressure;
      readonly attribute Basics::Optional_Double humidity;
      readonly attribute Basics::Optional_Double precipitation;
      readonly attribute Basics::Optional_Double windspeed;
      readonly attribute Basics::Optional_Double winddirection;
      readonly attribute Basics::Optional_Double cloudcover;
      readonly attribute Basics::Optional_Double uv_index;
      readonly attribute Basics::Optional_Long   weathercode;
      readonly attribute Basics::Optional_String summary;
   };

};
